sudo: required
dist: trusty

service:
  - docker

script:
  - docker build -t homeofficeckan .
  - sudo docker run -d --privileged=true --name=solr quay.io/ukhomeofficedigital/ckan-solr:v0.1.0
  - sudo docker run -d --privileged=true --name=db ckan/postgresql

  - sudo docker run -d --privileged=true --name=ckan -e CKAN_SOLR_URL=http://solr:8983/solr/ckan -p 5000:5000 --link db:db --link solr:solr homeofficeckan
  - sleep 60
  - curl -k -o /tmp/homeofficeckan.output.html http://localhost:5000

after_failure:
  - docker logs ckan
